### PR TITLE
Client error propagation

### LINKED ISSUE #66: Premature stream termination is not propagated
**What happened**:
Premature termination of the gRPC stream (either due to client cancellation or sidecar detected error) must be propagated to the CSI driver by cancelling the context used to create the stream.

For example, we have logic that looks like this:
```
func (s *Server) GetMetadataAllocated(req *api.GetMetadataAllocatedRequest, stream api.SnapshotMetadata_GetMetadataAllocatedServer) error {
        ...
        ctx := stream.Context()
	csiStream, err := csi.NewSnapshotMetadataClient(s.csiConnection()).GetMetadataAllocated(ctx, csiReq)
	for {
		csiResp, err := csiStream.Recv()

		if err := clientStream.Send(clientResp); err != nil {
			return s.statusPassOrWrapError(err, codes.Internal, msgInternalFailedToSendResponseFmt, err)
		}
	}
}
```
A failure to send to the client unwinds in the sidecar, but does not cancel the downstream CSI driver - it would block on its `Send` call until it times out (if it had set a timeout).

**What you expected to happen**:

We should be doing the equivalent of this:
```
func (s *Server) GetMetadataAllocated(req *api.GetMetadataAllocatedRequest, stream api.SnapshotMetadata_GetMetadataAllocatedServer) error {
        ...
        ctx, cancelFn := context.WithCancel(stream.Context())
        defer cancelFn()

	csiStream, err := csi.NewSnapshotMetadataClient(s.csiConnection()).GetMetadataAllocated(ctx, csiReq)
	for {
		csiResp, err := csiStream.Recv()

		if err := clientStream.Send(clientResp); err != nil {
			return s.statusPassOrWrapError(err, codes.Internal, msgInternalFailedToSendResponseFmt, err)
		}
	}
}
```
Here the deferred cancel function would force cancellation of the CSI driver's stream either when a local error is detected or if the sidecar's client cancelled its stream.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by carlbraganza**
Ensure that client errors (context cancellation or failure to read responses) will result in the CSI driver stream being canceled.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This ensures that when a client aborts its receive stream, or stops reading responses, or the network connection between the client and the sidecar fails, the CSI driver stream will get canceled.

**Which issue(s) this PR fixes**:

Fixes #66

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cmd/csi-snapshot-metadata/Dockerfile [hunk 1]
```diff
@@ -1,5 +1,5 @@
 FROM alpine AS builder
-ARG GRPC_HEALTH_PROBE_VERSION=v0.4.34
+ARG GRPC_HEALTH_PROBE_VERSION=v0.4.35
```
Comment (carlbraganza) [inline cmd/csi-snapshot-metadata/Dockerfile:2]: This was motivated by the failing vulnerability test.

File: pkg/internal/server/grpc/server.go [hunk 2]
```diff
@@ -40,10 +41,18 @@ import (
 const (
 	HandlerTraceLogLevel         = 4
 	HandlerDetailedTraceLogLevel = 5
+
+	HandlerDefaultMaxStreamDuration = time.Minute * 60
```
Comment (Rakshith-R) [inline pkg/internal/server/grpc/server.go:45]:
```suggestion
	HandlerDefaultMaxStreamDuration = time.Minute * 10
```
This should be 10 minutes ? 
the same value as `defaultMaxStreamingDurationMin = 10`

File: pkg/internal/server/grpc/get_metadata_allocated.go [hunk 3]
```diff
@@ -31,7 +31,11 @@ import (
 )
 
 func (s *Server) GetMetadataAllocated(req *api.GetMetadataAllocatedRequest, stream api.SnapshotMetadata_GetMetadataAllocatedServer) error {
-	ctx := s.getMetadataAllocatedContextWithLogger(req, stream)
+	// Create a timeout context so that failure in either sending to the client or
+	// receiving from the CSI driver will ultimately abort the handler session.
+	// The context could also get canceled by the client.
+	ctx, cancelFn := context.WithTimeout(s.getMetadataAllocatedContextWithLogger(req, stream), s.config.MaxStreamDur)
```
Comment (PrasadG193) [inline pkg/internal/server/grpc/get_metadata_allocated.go:37]: just to confirm, this timeout will be applicable for take taken for complete data transfer not just a page (maxResults), right?

**Review by PrasadG193 — APPROVED** [review]
/lgtm
/approve
